// Datos de fábrica cargados desde el Excel provisto (módulos LED y equipos de
// video: senders, escaladores, media servers, procesadores). Se usan para
// sembrar las tablas la primera vez que se abre el módulo LED (si están
// vacías), igual que seedUsuariosIniciales() en usuariosApi.js.

export const LED_MODULOS_SEED = [
  {
    "codigo": "RPMO0001",
    "nombre": "MODULO DE PANTALLA P6 PISO",
    "pitch": 6,
    "anchoMm": 500,
    "altoMm": 500,
    "pitchAnchoPx": 83.3,
    "pitchAltoPx": 83.3,
    "ancho1mPx": 166,
    "alto1mPx": 166,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0002",
    "nombre": "MODULO PANTALLA ESF P10-INDOOR",
    "pitch": 10,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0003",
    "nombre": "MODULO PANTALLA MESH P10-INDOOR",
    "pitch": 10,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0006",
    "nombre": "MODULO PANTALLA P2.6 RECTA",
    "pitch": 2.6,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 192,
    "pitchAltoPx": 384,
    "ancho1mPx": 384,
    "alto1mPx": 384,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0029",
    "nombre": "MODULO PANTALLA P2.6 CURVA",
    "pitch": 2.6,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 192,
    "pitchAltoPx": 384,
    "ancho1mPx": 384,
    "alto1mPx": 384,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0043",
    "nombre": "MODULO PANTALLA P8 PUB (1.024 mts x 1.024 mts)",
    "pitch": 8,
    "anchoMm": 1024,
    "altoMm": 1024,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 128,
    "ancho1mPx": 125,
    "alto1mPx": 125,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0041",
    "nombre": "MODULO PANTALLA P6.67 ESTADIO",
    "pitch": 6.67,
    "anchoMm": 960,
    "altoMm": 960,
    "pitchAnchoPx": 143,
    "pitchAltoPx": 143,
    "ancho1mPx": 149,
    "alto1mPx": 149,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0010",
    "nombre": "MODULO PANTALLA P5-LINSN",
    "pitch": 5,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0018",
    "nombre": "MODULO PANTALLA TRANSP P8-INDOOR",
    "pitch": 8,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 62.5,
    "pitchAltoPx": 125,
    "ancho1mPx": 125,
    "alto1mPx": 125,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0020",
    "nombre": "MODULO PANTALLA P10 1,20 X 1,20 PUB",
    "pitch": 10,
    "anchoMm": 1200,
    "altoMm": 1200,
    "pitchAnchoPx": 120,
    "pitchAltoPx": 120,
    "ancho1mPx": 100,
    "alto1mPx": 100,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0021",
    "nombre": "MODULO PANTALLA P10 0,96 X 0,96 PUB",
    "pitch": 10,
    "anchoMm": 960,
    "altoMm": 960,
    "pitchAnchoPx": 96,
    "pitchAltoPx": 96,
    "ancho1mPx": 100,
    "alto1mPx": 100,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0022",
    "nombre": "MODULO PANTALLA P8 1,024x1,024 PUB",
    "pitch": 8,
    "anchoMm": 1024,
    "altoMm": 1024,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 128,
    "ancho1mPx": 125,
    "alto1mPx": 125,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0031",
    "nombre": "MODULO PANTALLA P2.5 LAMP",
    "pitch": 2.5,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0034",
    "nombre": "MODULO PANTALLA P4 PUB",
    "pitch": 4,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0042",
    "nombre": "MODULO PANTALLA P2.5 (0.64 x 0.48mts)",
    "pitch": 2.5,
    "anchoMm": 640,
    "altoMm": 480,
    "pitchAnchoPx": 256,
    "pitchAltoPx": 192,
    "ancho1mPx": 400,
    "alto1mPx": 400,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0045",
    "nombre": "MODULO TOTEM SUBTE P2.9 (2x1mt)",
    "pitch": 2.9,
    "anchoMm": 2000,
    "altoMm": 1000,
    "pitchAnchoPx": 690,
    "pitchAltoPx": 345,
    "ancho1mPx": 345,
    "alto1mPx": 345,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0046",
    "nombre": "MODULO PANTALLA INDOOR P3.9 (0.5x1mt)",
    "pitch": 3.9,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 256,
    "ancho1mPx": 256,
    "alto1mPx": 256,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0047",
    "nombre": "MODULO PANTALLA INDOOR P2.5 (0.64 x 0.48)",
    "pitch": 2.5,
    "anchoMm": 640,
    "altoMm": 480,
    "pitchAnchoPx": 256,
    "pitchAltoPx": 192,
    "ancho1mPx": 400,
    "alto1mPx": 400,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0048",
    "nombre": "MODULO PANTALLA FIJA P2.5 (0.64x0.48mts)",
    "pitch": 2.5,
    "anchoMm": 640,
    "altoMm": 480,
    "pitchAnchoPx": 256,
    "pitchAltoPx": 192,
    "ancho1mPx": 400,
    "alto1mPx": 400,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0052",
    "nombre": "MODULO P2.6 INDOOR (0.5x0.5)",
    "pitch": 2.6,
    "anchoMm": 500,
    "altoMm": 500,
    "pitchAnchoPx": 192,
    "pitchAltoPx": 192,
    "ancho1mPx": 384,
    "alto1mPx": 384,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0007",
    "nombre": "MODULO PANTALLA P3-INDOOR",
    "pitch": 3,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0008",
    "nombre": "MODULO PANTALLA P3-INDOOR LINSN",
    "pitch": 3,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 166,
    "pitchAltoPx": 333,
    "ancho1mPx": 333,
    "alto1mPx": 333,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0009",
    "nombre": "MODULO PANTALLA P4-INDOOR",
    "pitch": 4,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0017",
    "nombre": "MODULO PANTALLA TRANSP P5-INDOOR",
    "pitch": 5,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0028",
    "nombre": "MODULO PANTALLA TRIANGULO P3.9 YESTECH",
    "pitch": 3.9,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0019",
    "nombre": "MODULO PANTALLA P12-PUB",
    "pitch": 12,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0027",
    "nombre": "MODULO PANTALLA CUADRADO P3.9 YESTECH",
    "pitch": 3.9,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0012",
    "nombre": "MODULO PANTALLA P6 CURVA-OUTDOOR",
    "pitch": 6,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0015",
    "nombre": "MODULO PANTALLA P8-OUTDOOR",
    "pitch": 8,
    "anchoMm": 960,
    "altoMm": 960,
    "pitchAnchoPx": 120,
    "pitchAltoPx": 120,
    "ancho1mPx": 125,
    "alto1mPx": 125,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0016",
    "nombre": "MODULO PANTALLA P8 PISO",
    "pitch": 8,
    "anchoMm": 500,
    "altoMm": 500,
    "pitchAnchoPx": 62.5,
    "pitchAltoPx": 62.5,
    "ancho1mPx": 125,
    "alto1mPx": 125,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0026",
    "nombre": "MODULO PANTALLA P4.81 OUTDOOR",
    "pitch": 4.81,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 103,
    "pitchAltoPx": 207,
    "ancho1mPx": 207,
    "alto1mPx": 207,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0011",
    "nombre": "MODULO PANTALLA P5-INDOOR",
    "pitch": 5,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0013",
    "nombre": "MODULO PANTALLA P6-INDOOR",
    "pitch": 6,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0037",
    "nombre": "MODULO PANTALLA P4.81 FIJA (1m x 0.50m)",
    "pitch": 4.81,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 208,
    "pitchAltoPx": 104,
    "ancho1mPx": 208,
    "alto1mPx": 208,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0049",
    "nombre": "MODULO P4.81 OUTDOOR ( 0.5 x 1 mts)",
    "pitch": 4.81,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 104,
    "pitchAltoPx": 208,
    "ancho1mPx": 208,
    "alto1mPx": 208,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0014",
    "nombre": "MODULO PANTALLA P6-OUTDOOR",
    "pitch": 6,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0025",
    "nombre": "MODULO P5 INDOOR 0.64 X 0.64",
    "pitch": 5,
    "anchoMm": 640,
    "altoMm": 640,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 128,
    "ancho1mPx": 200,
    "alto1mPx": 200,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0030",
    "nombre": "MODULO PANTALLA P3.9 LAMP (0.50 x 0.50)",
    "pitch": 3.9,
    "anchoMm": 500,
    "altoMm": 500,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 128,
    "ancho1mPx": 256,
    "alto1mPx": 256,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0038",
    "nombre": "MODULO PANTALLA P3.9 INDOOR- 1 MTS X 0.50 MTS",
    "pitch": 3.9,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 256,
    "pitchAltoPx": 128,
    "ancho1mPx": 256,
    "alto1mPx": 256,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0024",
    "nombre": "MODULO PANTALLA P8 MESH",
    "pitch": 8,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0050",
    "nombre": "MODULO P8 LED OUTDOOR (0.96x0.96)",
    "pitch": 8,
    "anchoMm": 960,
    "altoMm": 960,
    "pitchAnchoPx": 120,
    "pitchAltoPx": 120,
    "ancho1mPx": 125,
    "alto1mPx": 125,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0039",
    "nombre": "MODULO PANTALLA P3.9 MICROLED INDOOR 0.50 MTS X 0.50 MTS  CURVA",
    "pitch": 3.9,
    "anchoMm": 500,
    "altoMm": 500,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 128,
    "ancho1mPx": 256,
    "alto1mPx": 256,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0051",
    "nombre": "MODULO P10 (0.96x0.96)",
    "pitch": 10,
    "anchoMm": 960,
    "altoMm": 960,
    "pitchAnchoPx": 96,
    "pitchAltoPx": 96,
    "ancho1mPx": 100,
    "alto1mPx": 100,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0044",
    "nombre": "MODULO PANTALLA P5 FIJA (1.6m x 0.80m)",
    "pitch": 5,
    "anchoMm": 1600,
    "altoMm": 800,
    "pitchAnchoPx": 320,
    "pitchAltoPx": 160,
    "ancho1mPx": 200,
    "alto1mPx": 200,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0054",
    "nombre": "MODULO P8 OUTDOOR (0,96X0,96) PARTIDA II",
    "pitch": 8,
    "anchoMm": 960,
    "altoMm": 960,
    "pitchAnchoPx": 120,
    "pitchAltoPx": 120,
    "ancho1mPx": 125,
    "alto1mPx": 125,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0055",
    "nombre": "MODULO P8 OUTDOOR (0,96X0,96) PARTIDA III",
    "pitch": 8,
    "anchoMm": 960,
    "altoMm": 960,
    "pitchAnchoPx": 120,
    "pitchAltoPx": 120,
    "ancho1mPx": 125,
    "alto1mPx": 125,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0058",
    "nombre": "MODULO P3.91 TECHLED (0,50X1)",
    "pitch": 3.91,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 256,
    "ancho1mPx": 256,
    "alto1mPx": 256,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0059",
    "nombre": "MODULO PANTALLA P3.9 UNILUMIN 0,5 X 1",
    "pitch": 3.9,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 256,
    "ancho1mPx": 256,
    "alto1mPx": 256,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0061",
    "nombre": "MODULO PANTALLA ULF 2.6 UNILUMIN",
    "pitch": 2.6,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0063",
    "nombre": "MODULO PANTALLA P3.9 UGM 2 P-933",
    "pitch": 3.9,
    "anchoMm": 500,
    "altoMm": 500,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 128,
    "ancho1mPx": 256,
    "alto1mPx": 256,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0064",
    "nombre": "MODULO PANTALLA P5 BUS",
    "pitch": 5,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0065",
    "nombre": "MODULO PANTALLA UGNII2.6 500*500",
    "pitch": 2.6,
    "anchoMm": 500,
    "altoMm": 500,
    "pitchAnchoPx": 192,
    "pitchAltoPx": 192,
    "ancho1mPx": 384,
    "alto1mPx": 384,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0066",
    "nombre": "MODULO PANTALLA RNS 2.9",
    "pitch": 2.9,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 172,
    "pitchAltoPx": 344,
    "ancho1mPx": 344,
    "alto1mPx": 344,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0071",
    "nombre": "MODULO RNCX 3.9 0,5X0,5 INDOOR",
    "pitch": 3.9,
    "anchoMm": 500,
    "altoMm": 500,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 128,
    "ancho1mPx": 256,
    "alto1mPx": 256,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0070",
    "nombre": "MODULO RNCX 3.9 1MTS X 0,5 INDOOR",
    "pitch": 3.9,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 256,
    "pitchAltoPx": 128,
    "ancho1mPx": 256,
    "alto1mPx": 256,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0072",
    "nombre": "MODULO PANTALLA P2.6 AUDP2 (500 x 500)",
    "pitch": 2.6,
    "anchoMm": 500,
    "altoMm": 500,
    "pitchAnchoPx": 192,
    "pitchAltoPx": 192,
    "ancho1mPx": 385,
    "alto1mPx": 385,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0073",
    "nombre": "MODULO PANTALLA P5 0.96X0.96 PARTIDA II",
    "pitch": 5,
    "anchoMm": 960,
    "altoMm": 960,
    "pitchAnchoPx": 192,
    "pitchAltoPx": 192,
    "ancho1mPx": 200,
    "alto1mPx": 200,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0074",
    "nombre": "MODULO PANTALLA P6 0.96X0.96 PARTIDA II",
    "pitch": 6,
    "anchoMm": 960,
    "altoMm": 960,
    "pitchAnchoPx": 160,
    "pitchAltoPx": 160,
    "ancho1mPx": 167,
    "alto1mPx": 167,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0075",
    "nombre": "MODULO PANTALLA P8 0.96X0.96 PARTIDA II",
    "pitch": 8,
    "anchoMm": 960,
    "altoMm": 960,
    "pitchAnchoPx": 120,
    "pitchAltoPx": 120,
    "ancho1mPx": 125,
    "alto1mPx": 125,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0076",
    "nombre": "MODULO P3.9 0.50 X 1.00 BLACK LED X1000",
    "pitch": 3.9,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 256,
    "ancho1mPx": 256,
    "alto1mPx": 256,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0077",
    "nombre": "MODULO P3.9 0.50 X 0.50 BLACK LED X500",
    "pitch": 3.9,
    "anchoMm": 500,
    "altoMm": 500,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 128,
    "ancho1mPx": 256,
    "alto1mPx": 256,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0078",
    "nombre": "MODULO P3.9 ESQUINERO BLACK LED VR",
    "pitch": 3.9,
    "anchoMm": null,
    "altoMm": null,
    "pitchAnchoPx": null,
    "pitchAltoPx": null,
    "ancho1mPx": null,
    "alto1mPx": null,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0079",
    "nombre": "MODULO PANTALLA LED P8 0.96 X 0.96",
    "pitch": 8,
    "anchoMm": 960,
    "altoMm": 960,
    "pitchAnchoPx": 120,
    "pitchAltoPx": 120,
    "ancho1mPx": 125,
    "alto1mPx": 125,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0080",
    "nombre": "MODULO PANTALLA LED P8 1.280 X 0.96",
    "pitch": 8,
    "anchoMm": 1280,
    "altoMm": 960,
    "pitchAnchoPx": 160,
    "pitchAltoPx": 120,
    "ancho1mPx": 125,
    "alto1mPx": 125,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0081",
    "nombre": "MODULO PANTALLA LED CURVA P8 0.96 X 0.96",
    "pitch": 8,
    "anchoMm": 960,
    "altoMm": 960,
    "pitchAnchoPx": 120,
    "pitchAltoPx": 120,
    "ancho1mPx": 125,
    "alto1mPx": 125,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0085",
    "nombre": "MODULO 3.9 BLACK LED FC FLEXIBLE",
    "pitch": 3.9,
    "anchoMm": 500,
    "altoMm": 500,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 128,
    "ancho1mPx": 256,
    "alto1mPx": 256,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0089",
    "nombre": "MODULO BLACK LED SPIDER P-1.95",
    "pitch": 1.95,
    "anchoMm": 500,
    "altoMm": 500,
    "pitchAnchoPx": 256,
    "pitchAltoPx": 256,
    "ancho1mPx": 512,
    "alto1mPx": 512,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0090",
    "nombre": "MODULO 3.9 MASTER PLUS X1000",
    "pitch": 3.9,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 256,
    "ancho1mPx": 256,
    "alto1mPx": 256,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0091",
    "nombre": "MODULO P3.9 BLACK LED OX 50X50",
    "pitch": 3.9,
    "anchoMm": 500,
    "altoMm": 500,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 128,
    "ancho1mPx": 256,
    "alto1mPx": 256,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0092",
    "nombre": "MODULO URMIII-03 OUTDOOR CURVA X1000",
    "pitch": 3.9,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 256,
    "ancho1mPx": 256,
    "alto1mPx": 256,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0094",
    "nombre": "MODULO URMIII03-C OUTDOOR 500x500",
    "pitch": 3.9,
    "anchoMm": 500,
    "altoMm": 500,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 128,
    "ancho1mPx": 256,
    "alto1mPx": 256,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0087-V",
    "nombre": "MODULO LAMPRO 2.5 - VENTA",
    "pitch": 2.5,
    "anchoMm": 320,
    "altoMm": 480,
    "pitchAnchoPx": 128,
    "pitchAltoPx": 192,
    "ancho1mPx": 400,
    "alto1mPx": 400,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO0088-V",
    "nombre": "MODULO LAMPRO 1.8 - VENTA",
    "pitch": 1.8,
    "anchoMm": 320,
    "altoMm": 480,
    "pitchAnchoPx": 172,
    "pitchAltoPx": 266,
    "ancho1mPx": 555,
    "alto1mPx": 555,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO1777",
    "nombre": "MODULO 3.91 LED DISPLAY OUTDOOR- (0.50 X 1) - Verde",
    "pitch": 3.91,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 127,
    "pitchAltoPx": 255,
    "ancho1mPx": 255,
    "alto1mPx": 255,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO1828",
    "nombre": "Modulo P8 - VESTA - RECTA (0.96 x 0.96)",
    "pitch": 8,
    "anchoMm": 960,
    "altoMm": 960,
    "pitchAnchoPx": 120,
    "pitchAltoPx": 120,
    "ancho1mPx": 125,
    "alto1mPx": 125,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO1829",
    "nombre": "Modulo P8 - VESTA - CURVA (0.96 x 0.96)",
    "pitch": 8,
    "anchoMm": 960,
    "altoMm": 960,
    "pitchAnchoPx": 120,
    "pitchAltoPx": 120,
    "ancho1mPx": 125,
    "alto1mPx": 125,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO1830",
    "nombre": "Modulo P5 - Lucina (0,96mm x 0,96mm)",
    "pitch": 5,
    "anchoMm": 960,
    "altoMm": 960,
    "pitchAnchoPx": 192,
    "pitchAltoPx": 192,
    "ancho1mPx": 200,
    "alto1mPx": 200,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO1831",
    "nombre": "Modulo P8 - CERES (0.96mm x 0.96mm)",
    "pitch": 8,
    "anchoMm": 960,
    "altoMm": 960,
    "pitchAnchoPx": 120,
    "pitchAltoPx": 120,
    "ancho1mPx": 125,
    "alto1mPx": 125,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  },
  {
    "codigo": "RPMO1832",
    "nombre": "MODULO 3.91 - HELIOS (500mm x 1000mm)",
    "pitch": 3.91,
    "anchoMm": 500,
    "altoMm": 1000,
    "pitchAnchoPx": 127,
    "pitchAltoPx": 255,
    "ancho1mPx": 255,
    "alto1mPx": 255,
    "carpeta": "JUPITERLED/PANTALLAS LED/MODULOS",
    "tipoEquipo": "Artículo físico"
  }
];

export const LED_EQUIPOS_SEED = [
  {
    "codigo": "RVCO0010",
    "nombre": "REPRODUCTOR DATA VIDEO C/FUENTE",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVME0001",
    "nombre": "MEDIA SERVER d3 2X2",
    "carpeta": "JUPITERLED/VIDEO/MEDIA SERVER",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVME0002",
    "nombre": "MEDIA SERVER d3 4 x v2.5",
    "carpeta": "JUPITERLED/VIDEO/MEDIA SERVER",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVME0003",
    "nombre": "MEDIA SERVER D3 4X4 DP OUTPUT",
    "carpeta": "JUPITERLED/VIDEO/MEDIA SERVER",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVME0004",
    "nombre": "MEDIA SERVER D3 4X4 DVI OUTPUT",
    "carpeta": "JUPITERLED/VIDEO/MEDIA SERVER",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVME0005",
    "nombre": "MEDIA SERVER D3 GX2",
    "carpeta": "JUPITERLED/VIDEO/MEDIA SERVER",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVPR0002",
    "nombre": "ESCALADOR  UVP 100",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVPR0003",
    "nombre": "ESCALADOR ANALOG WAY 4K BIO",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVPR0004",
    "nombre": "ESCALADOR FOLSOM IMAGE PRO II",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVPR0006",
    "nombre": "ESCALADOR RGB LINK VSP 5162",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVPR0007",
    "nombre": "ESCALADOR VDWALL LVP605S",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVPR0008",
    "nombre": "ESCALADOR VENUS X1 PRO CON INPUT SDI",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVPR0009",
    "nombre": "ESCALADOR VENUS X1 RGB LINK",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVPR0010",
    "nombre": "ESCALADOR VENUS X3 RGB LINK",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVPR0011",
    "nombre": "HDMI &SDI ESCALADOR DATA VIDEO",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVPR0012",
    "nombre": "REPRODUCTOR DE VIDEO NOVASTAR PBOX-150",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVPR0013",
    "nombre": "REPRODUCTOR DE VIDEO RGBLINK FLEX DS1",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVPR0014",
    "nombre": "REPRODUCTOR DE VIDEO VDWALL",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVPR0015",
    "nombre": "ESCALADOR VDWALL LVP615S",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVPR0016",
    "nombre": "ESCALADOR VDWALL 609S 4K",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0001",
    "nombre": "SENDER 4K MCTRL4K",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 16,
    "puertosFibra": 4,
    "capacidadMaxPixeles": null,
    "resolucion": "4096×2160 @ 60Hz",
    "maximoAltoAncho": "7680 píxeles",
    "inputHdmi": 1,
    "inputDisplayport": 1,
    "inputDvi": 2,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0002",
    "nombre": "SENDER G3 NET  DOBLE PLACA  LINSN + ESCALADOR",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0003",
    "nombre": "SENDER LINSN X 4 PLACAS 802D",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0004",
    "nombre": "SENDER PLACAS  LINSN 802D",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0005",
    "nombre": "SENDER SD700",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0006",
    "nombre": "SENDERS C3.0 PANTALLA MESH",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0007",
    "nombre": "SENDERS LINSN AZUL",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0008",
    "nombre": "SENDERS NOVA 300E",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0009",
    "nombre": "SENDERS NOVA 660 MCTRL",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 4,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": "1920×1200 a 60 Hz",
    "maximoAltoAncho": null,
    "inputHdmi": 1,
    "inputDisplayport": 1,
    "inputDvi": 1,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0010",
    "nombre": "SENDERS NOVA MCTRL600",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 4,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": "1920×1200 a 60 Hz",
    "maximoAltoAncho": null,
    "inputHdmi": 1,
    "inputDisplayport": null,
    "inputDvi": 1,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0011",
    "nombre": "SENDERS NOVA MSD600E",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 4,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": "1920×1200 a 60 Hz",
    "maximoAltoAncho": null,
    "inputHdmi": 1,
    "inputDisplayport": null,
    "inputDvi": 1,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0012",
    "nombre": "SENDERS NOVA SD500E",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0013",
    "nombre": "SENDERS PLACA ESFERAS",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0014",
    "nombre": "SENDERS PLACAS NOVA MSD300",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0015",
    "nombre": "SENDERS TACTIL PANTALLA MESH",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0016",
    "nombre": "SENDER LINSN X 1 PLACA 802D",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0017",
    "nombre": "SENDER BOX LINSN",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0018",
    "nombre": "SENDERS MCTRL 300",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 2,
    "puertosFibra": null,
    "capacidadMaxPixeles": 1300000,
    "resolucion": "1280×1024",
    "maximoAltoAncho": "3840 alto o 1920 alto",
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": 1,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0019",
    "nombre": "SENDER TAURUS TB2",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 1,
    "puertosFibra": null,
    "capacidadMaxPixeles": 650000,
    "resolucion": null,
    "maximoAltoAncho": "1920 ancho o 1080 alto",
    "inputHdmi": 1,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": true,
    "observaciones": null
  },
  {
    "codigo": "RVSE0020",
    "nombre": "SENDER MCTRL R5",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0021",
    "nombre": "SENDER TB3",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 2,
    "puertosFibra": null,
    "capacidadMaxPixeles": 650000,
    "resolucion": null,
    "maximoAltoAncho": "1920 de alto",
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": true,
    "observaciones": null
  },
  {
    "codigo": "RVSE0022",
    "nombre": "SENDER TAURUS TB1",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 1,
    "puertosFibra": null,
    "capacidadMaxPixeles": 650000,
    "resolucion": null,
    "maximoAltoAncho": "1920 ancho o 1080 alto",
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": true,
    "observaciones": null
  },
  {
    "codigo": "RVSE0023",
    "nombre": "SENDERS PLACA NOVA MSD600",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0024",
    "nombre": "CVT4KS",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 16,
    "puertosFibra": 2,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": "conversor de fibra a ethernet/ necesita un sender"
  },
  {
    "codigo": "RVSE0025",
    "nombre": "SENDER NOVA PRO UHD JR",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 16,
    "puertosFibra": 4,
    "capacidadMaxPixeles": 10400000,
    "resolucion": "Ultra HD 4K×2K a 60 Hz",
    "maximoAltoAncho": null,
    "inputHdmi": 1,
    "inputDisplayport": 1,
    "inputDvi": 4,
    "inputSdi": 2,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0030",
    "nombre": "SENDER MCTRL 660 PRO",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 6,
    "puertosFibra": 2,
    "capacidadMaxPixeles": 2300000,
    "resolucion": "1920×1200 a 60 Hz",
    "maximoAltoAncho": null,
    "inputHdmi": 1,
    "inputDisplayport": null,
    "inputDvi": 1,
    "inputSdi": 1,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVPR0018",
    "nombre": "H5 VIDEO WALL SPLICER NOVASTAR",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": 39000000,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": "modulos de input y output intecambiables"
  },
  {
    "codigo": "RVPR0019",
    "nombre": "H2 VIDEO WALL SPLICER NOVASTAR",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": 26000000,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": "modulos de input y output intecambiables"
  },
  {
    "codigo": "RVSE0031",
    "nombre": "SENDER T1",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0026",
    "nombre": "SENDER MCTRL 700",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 6,
    "puertosFibra": null,
    "capacidadMaxPixeles": 2300000,
    "resolucion": "1920×1200 a 60 Hz",
    "maximoAltoAncho": null,
    "inputHdmi": 1,
    "inputDisplayport": null,
    "inputDvi": 1,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0032",
    "nombre": "NOVA CONTROL CARD TCC70G P5 BUS",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVME0008",
    "nombre": "MEDIA SERVER TECNOPOLIS",
    "carpeta": "JUPITERLED/VIDEO/MEDIA SERVER",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0033",
    "nombre": "SENDER NOVASTAR MX 40",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 20,
    "puertosFibra": 2,
    "capacidadMaxPixeles": 8800000,
    "resolucion": "4096×2160 a 60 Hz",
    "maximoAltoAncho": null,
    "inputHdmi": 3,
    "inputDisplayport": 1,
    "inputDvi": null,
    "inputSdi": 1,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0039",
    "nombre": "TAURUS POSTE LED P2.6",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVCS0018",
    "nombre": "MAGIC BOX",
    "carpeta": "JUPITERLED/VIDEO/MEDIA SERVER",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RPRE1011",
    "nombre": "TAPA + TAURUS + FUENTE POSTE LED P2.6",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVCS0019",
    "nombre": "MAGIC BOX WHITE EDITION",
    "carpeta": "JUPITERLED/VIDEO/MEDIA SERVER",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVPR0024",
    "nombre": "H9 VIDEO WALL SPLICER NOVASTAR",
    "carpeta": "JUPITERLED/VIDEO/MEDIA SERVER",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": 65000000,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": "modulos de input y output intecambiables"
  },
  {
    "codigo": "RVSE0035",
    "nombre": "MX6000 PRO",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": null,
    "puertosFibra": null,
    "capacidadMaxPixeles": 141000000,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": "modulos de input y output intecambiables"
  },
  {
    "codigo": "RVSE0036",
    "nombre": "CVT10 PRO-S",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 10,
    "puertosFibra": 2,
    "capacidadMaxPixeles": null,
    "resolucion": null,
    "maximoAltoAncho": null,
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": false,
    "observaciones": "conversor de fibra a ethernet/ necesita un sender"
  },
  {
    "codigo": "RVPR0025",
    "nombre": "LED PLAYBACK CONTROL PROCESSOR TU4K PRO",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Combinación física",
    "puertosEthernet": 20,
    "puertosFibra": 2,
    "capacidadMaxPixeles": 13000000,
    "resolucion": null,
    "maximoAltoAncho": "16,384 píxeles de ancho o hasta 8,192 píxeles de alto",
    "inputHdmi": 3,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": true,
    "observaciones": null
  },
  {
    "codigo": "RVSE0037",
    "nombre": "SENDER TAURUS TB40",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 2,
    "puertosFibra": null,
    "capacidadMaxPixeles": 1300000,
    "resolucion": null,
    "maximoAltoAncho": "4096 píxeles o un alto de hasta 4096 píxeles",
    "inputHdmi": 1,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": true,
    "observaciones": null
  },
  {
    "codigo": "RVPR0026",
    "nombre": "LED PLAYBACK CONTROL PROCESSOR TU15 PRO",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 4,
    "puertosFibra": null,
    "capacidadMaxPixeles": 2600000,
    "resolucion": null,
    "maximoAltoAncho": "4096 píxeles de ancho o hasta 1920 píxeles de alto.",
    "inputHdmi": 2,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": true,
    "observaciones": null
  },
  {
    "codigo": "RVPR0027",
    "nombre": "LED PLAYBACK CONTROL PROCESSOR TU20 PRO",
    "carpeta": "JUPITERLED/VIDEO/PROCESADOR DE VIDEO",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 6,
    "puertosFibra": null,
    "capacidadMaxPixeles": 3900000,
    "resolucion": null,
    "maximoAltoAncho": "4096 píxeles o un alto de hasta 1920 píxeles",
    "inputHdmi": 2,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": true,
    "observaciones": null
  },
  {
    "codigo": "RVSE0038",
    "nombre": "VX2000 Pro",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 20,
    "puertosFibra": 4,
    "capacidadMaxPixeles": 13000000,
    "resolucion": null,
    "maximoAltoAncho": "ancho 16,384 píxeles o una altura máxima de hasta 8,192 píxeles",
    "inputHdmi": 6,
    "inputDisplayport": 1,
    "inputDvi": null,
    "inputSdi": 1,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE7777",
    "nombre": "VX1000 SENDER",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 10,
    "puertosFibra": 2,
    "capacidadMaxPixeles": 6500000,
    "resolucion": null,
    "maximoAltoAncho": "ancho 10,240 píxeles o una altura máxima de hasta 8,192 píxeles",
    "inputHdmi": 1,
    "inputDisplayport": null,
    "inputDvi": 1,
    "inputSdi": 1,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE1853",
    "nombre": "SENDER TAURUS TB10 PLUS",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 1,
    "puertosFibra": null,
    "capacidadMaxPixeles": 650000,
    "resolucion": null,
    "maximoAltoAncho": "ancho  2048 píxeles o una altura máxima de hasta 2048 píxeles",
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": true,
    "observaciones": null
  },
  {
    "codigo": "RVSE0040",
    "nombre": "NOVASTAR VSP1000",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 10,
    "puertosFibra": 2,
    "capacidadMaxPixeles": 6500000,
    "resolucion": null,
    "maximoAltoAncho": "ancho 10,240 píxeles o una altura máxima de hasta 8,192 píxeles",
    "inputHdmi": 2,
    "inputDisplayport": null,
    "inputDvi": 2,
    "inputSdi": 1,
    "contenidoInterno": false,
    "observaciones": null
  },
  {
    "codigo": "RVSE0041",
    "nombre": "SENDER TB30",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 2,
    "puertosFibra": null,
    "capacidadMaxPixeles": 650000,
    "resolucion": "4K a 60 Hz",
    "maximoAltoAncho": "ancho 4096 píxeles o una altura máxima de hasta 4096 píxeles",
    "inputHdmi": 1,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": true,
    "observaciones": null
  },
  {
    "codigo": "RVSE0042",
    "nombre": "SENDER TAURUS TB20",
    "carpeta": "JUPITERLED/VIDEO/SENDERS",
    "tipoEquipo": "Artículo físico",
    "puertosEthernet": 1,
    "puertosFibra": null,
    "capacidadMaxPixeles": 650000,
    "resolucion": "4K a 60 Hz",
    "maximoAltoAncho": "ancho 4096 píxeles o una altura máxima de hasta 4096 píxeles",
    "inputHdmi": null,
    "inputDisplayport": null,
    "inputDvi": null,
    "inputSdi": null,
    "contenidoInterno": true,
    "observaciones": null
  }
];
